Make decoding of `Raw` to configs consistent
gardener/gardener-extension-shoot-rsyslog-relp pull request #209
Opened 2024-12-12 09:41 UTC by RadaBDimitrova

**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
Whenever decoding is needed, it's now done using `runtime.DecodeInto()`.

**Which issue(s) this PR fixes**:
Fixes #202

**Special notes for your reviewer**:
N/A

**Release note**:

```other operator
NONE
```

2024-12-12 10:03 UTC, plkokanov commented
/test pull-gardener-extension-shoot-rsyslog-relp-e2e-kind

2024-12-12 12:25 UTC, plkokanov commented
https://prow.gardener.cloud/view/gs/gardener-prow/pr-logs/pull/gardener_gardener-extension-shoot-rsyslog-relp/209/pull-gardener-extension-shoot-rsyslog-relp-e2e-kind/1867148206291292160 passed successfully, however, it seems that the cleanup process was terminated before it could completely finish successfully:

```
Deleting cluster "gardener-local" ...
Deleted nodes: ["gardener-local-control-plane"]
make[1]: Leaving directory '/home/prow/go/src/github.com/gardener/gardener-extension-shoot-rsyslog-relp/gardener'
make: *** [Makefile:149: ci-e2e-kind] Terminated
wrapper.sh] [EARLY EXIT] Exit code was 143, not preserving due to interrupt signal
```

2024-12-12 12:26 UTC, plkokanov commented
/test pull-gardener-extension-shoot-rsyslog-relp-e2e-kind

2024-12-12 12:52 UTC, Kostov6 reviewed
You can drop `func decodeRsyslogRelpConfig` as it should be no longer in use

2024-12-13 07:28 UTC, Kostov6 reviewed
/lgtm

2024-12-13 07:55 UTC, plkokanov requested changes
Just one small cosmetic nit, otherwise looks good.

2024-12-13 07:55 UTC, plkokanov commented on pkg/admission/validator/shoot.go
```suggestion
```
Let's also use this PR to remove the unnecessary empty line here

2024-12-13 08:13 UTC, plkokanov requested changes

2024-12-13 08:13 UTC, plkokanov commented on pkg/admission/validator/shoot.go
> +	err := runtime.DecodeInto(decoder, []byte(auditdConfigString), auditdConfig)
Sorry, just noticed this on a second look - could you also use one line for the error checking in all occurrences? 
```suggestion
	if err := runtime.DecodeInto(decoder, []byte(auditdConfigString), auditdConfig); err != nil {
```

2024-12-13 10:12 UTC, RadaBDimitrova commented
/retest

2024-12-13 11:17 UTC, plkokanov reviewed
/lgtm
/approve

2024-12-13 11:18 UTC, merged