Bump github.com/gardener/gardener to 1.86.0
gardener/gardener-extension-shoot-rsyslog-relp pull request #57
Opened 2024-01-05 11:09 UTC by timuthy

**How to categorize this PR?**

/area open-source
/kind enhancement
**What this PR does / why we need it**:
This PR updates the `github.com/gardener/gardener` dependency to `v1.86.0`. As a consequence, admission CA and service certificates are now managed automatically. The vendor directory is removed as well.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Bump github.com/gardener/gardener to 1.86.0.
```
```breaking operator
CA and server certificates for the admission component are managed automatically. Passing custom certificates via Helm values is not supported anymore.
```
```other developer
The `vendor` directory was removed in favor of the `go mod cache`.
```

2024-02-21 10:44 UTC, ialidzhikov reviewed
Minor nit, otherwise lgtm.

2024-02-21 10:44 UTC, ialidzhikov commented on cmd/gardener-extension-shoot-rsyslog-relp-admission/app/app.go
> -				}
@plkokanov we should consider using APIReader to read the Project Secret in the admission component: https://github.com/gardener/gardener-extension-registry-cache/blob/3b520080f3e608720ab1c3bf1aeaa24ac31886ff/pkg/admission/validator/cache/shoot.go#L124-L128

Anyways, this is out of scope of @timuthy 's PR.

2024-02-21 19:30 UTC, plkokanov requested changes
Thanks for the PR! Just a few more nits that I saw.

2024-02-27 07:17 UTC, plkokanov commented
🚀 
/lgtm
/approve

2024-02-27 07:19 UTC, merged