Only use immutable tls secret
gardener/gardener-extension-shoot-rsyslog-relp pull request #76
Opened 2024-03-06 16:58 UTC by Kostov6

**How to categorize this PR?**

/area quality
/kind enhancement

**What this PR does / why we need it**:
This PR forces referenced tls secret resource to be immutable by rejecting shoot config if mutable

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/issues/2

**Special notes for your reviewer**:

**Release note**:

```noteworthy user
When changing referenced TLS secret in `shoot.spec.resources[]` the user should provide only immutable secret
```

2024-03-07 07:30 UTC, plkokanov commented
/assign

2024-03-07 10:10 UTC, plkokanov requested changes
Some comments inline.
Additionally, you should flag this as a breaking change.

2024-03-07 13:00 UTC, Kostov6 commented on pkg/utils/utils.go
> +	if secret.Immutable == nil || !*secret.Immutable {
Shouldn't it be `if !ptr.Deref(secret.Immutable, false) {`?

2024-03-07 13:53 UTC, Kostov6 commented
/retest

2024-03-13 12:13 UTC, Kostov6 commented on pkg/utils/utils.go
> +	if !ptr.Deref(secret.Immutable, false) {
Should the example secret in the document have a hash suffix?

2024-03-13 13:48 UTC, ialidzhikov commented on pkg/utils/utils.go
> +	if !ptr.Deref(secret.Immutable, false) {
It is already suffixed with v1 so I assume this v1 represents the revision of the Secret. At least this is also the naming pattern we use in the registry-cache docs when dealing with immutable Secrets: see the docs in https://github.com/gardener/gardener-extension-registry-cache/blob/9176c6572d582e0725024b1db30735d8c7f25cbc/docs/usage/registry-cache/upstream-credentials.md, you will find there `-v1` and `-v2` suffixes in the Secret names.

2024-03-15 11:41 UTC, plkokanov requested changes
Few more minor nits related to grammar and proper terms. 
We could also include this PR in the new release.

2024-03-15 11:41 UTC, plkokanov commented on docs/usage/configuration.md
> +The communication to the target server is not encrypted by default. To enable encryption, set the `.tls.enabled` field in the `shoot-rsyslog-relp` extension configuration to `true`. In this case, a i
nit:
```suggestion
The communication to the target server is not encrypted by default. To enable encryption, set the `.tls.enabled` field in the `shoot-rsyslog-relp` extension configuration to `true`. In this case, an immutable secret which contains the TLS certificates used to establish the TLS connection to the server must be created in the same project namespace as your Shoot.
```

2024-03-15 11:41 UTC, plkokanov commented on docs/usage/configuration.md
> +> **Note:**  The secret should be immutable
```suggestion
> **Note:**  The secret must be immutable
```

2024-03-15 11:41 UTC, plkokanov commented on pkg/utils/utils.go
> +		return fmt.Errorf("secret %s should be immutable", key.String())
```suggestion
		return fmt.Errorf("secret %s must be immutable", key.String())
```

2024-03-15 11:41 UTC, plkokanov commented on pkg/utils/utils_test.go
> +			MatchError(ContainSubstring("secret foo/rsyslog-secret should be immutable")),
```suggestion
			MatchError(ContainSubstring("secret foo/rsyslog-secret must be immutable")),
```

2024-03-28 07:07 UTC, Kostov6 commented
/retest

2024-04-12 10:36 UTC, ialidzhikov commented
/remove-lifecycle stale

2024-05-13 07:45 UTC, ialidzhikov commented
/remove-lifecycle rotten

2024-05-13 14:33 UTC, plkokanov commented
/unhold

2024-05-14 12:38 UTC, plkokanov commented
/lgtm
/approve

2024-05-14 13:24 UTC, merged