Drop support for Shoots with Kubernetes version == 1.24
gardener/gardener-extension-shoot-rsyslog-relp pull request #79
Opened 2024-03-14 10:36 UTC by Kostov6

**How to categorize this PR?**

/kind cleanup

**What this PR does / why we need it**:
- Add `unhealthyPodEvictionPolicy: AlwaysAllow` to PDBs
- Drop support for Shoots, Seeds and Gardens with Kubernetes version == 1.24.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/8921
Part of https://github.com/gardener/gardener/issues/8821

**Special notes for your reviewer**:
In draft until the gardener/gardener PR is merged and released.

**Release note**:

```breaking operator
`extension-shoot-rsyslog-relp` no longer supports Shoots with Кubernetes version == 1.24.
```

2024-03-14 14:22 UTC, plkokanov commented
/assign

2024-03-15 04:09 UTC, shafeeqes commented
There are more charts requiring cleanup, see https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/pull/55/commits/7037bbc31f6053025c829d5686d3cecd5f13d37d

2024-03-15 11:34 UTC, plkokanov requested changes
Thanks for the PR!
Just one minor nit inline.

2024-03-15 11:34 UTC, plkokanov commented on pkg/component/rsyslogrelpconfigcleaner/rsyslog_relp_config_cleaner.go
> +		objects []client.Object
You can remove this variable and just pass the `daemonSet` directly here: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/6dc16d1721fbd2fb9ff260aaebf35e5b868811f8/pkg/component/rsyslogrelpconfigcleaner/rsyslog_relp_config_cleaner.go#L168

2024-03-22 15:05 UTC, plkokanov commented
/lgtm
/approve

2024-03-22 15:06 UTC, merged